name: Label Nugget Discussions

on:
  discussion:
    types: [created, edited]

jobs:
  label_nugget:
    runs-on: ubuntu-latest
    steps:
    - name: Check for 'Nugget' keyword and add label
      uses: actions/github-script@v6
      with:
        script: |
          const discussion = context.payload.discussion;
          const nuggetLabel = 'Nugget';  # or 'Knowledge Nugget'
          
          // Check if the title or body contains the word "Nugget"
          if (discussion.title.includes('Nugget') || discussion.body.includes('Nugget')) {
            const labels = discussion.labels.map(label => label.name);

            // Add label if it's not already present
            if (!labels.includes(nuggetLabel)) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: discussion.number,
                labels: [nuggetLabel],
              });
              console.log(`Label '${nuggetLabel}' added to discussion #${discussion.number}`);
            }
          }
