name: Create Labels in Repositor

on:
  push:
    branches:
      - main

jobs:
  create_labels:
    runs-on: ubuntu-latest
    steps:
    - name: Create labels in the repository
      uses: actions/github-script@v6
      with:
        script: |
          const labelsToCreate = [
            { name: 'Nugget', color: 'ff5733', description: 'Knowledge Nuggets' },
            { name: 'Bug', color: 'f29513', description: 'Something is not working' },
            { name: 'Enhancement', color: 'a2eeef', description: 'New feature or request' },
            { name: 'Documentation', color: '0075ca', description: 'Improvements or additions to documentation' }
          ];

          for (const label of labelsToCreate) {
            try {
              // Try to create the label
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label.name,
                color: label.color,
                description: label.description
              });
              console.log(`Label '${label.name}' created successfully.`);
            } catch (error) {
              // If the label already exists, log a message
              if (error.status === 422) {
                console.log(`Label '${label.name}' already exists.`);
              } else {
                throw error;
              }
            }
          }
        github-token: ${{ secrets.G_TOKEN }}  # Replace with your GitHub token secret
